### ISSUE TITLE
"integrationDisabled"

### ISSUE THREAD

**Issue by tdevaney07** [webard/nova-zadarma#10]
I've set the SIP, the key and secret in the environment, however I'm getting this error:
integrationDisabled: Your integration with Zadarma is disabled or you've set a wrong key or sip.

Any insights?

**Comment by szepeviktor** [comment]
You could write a super simple example script
https://github.com/zadarma/user-api-v1/blob/bfdb7550b8f17e49b2928a84bfa0ec8587838806/examples/index.php#L1-L19
and find out whether it is this package or your credentials.

**Comment by tdevaney07** [comment]
It was not the package! It was my setup. I rolled my keys and also added my domain to webrtc (not sure if related), but in anycase, it works beautifully. Nice work, this is an incredible package!

**Comment by szepeviktor** [comment]
Glad to help.

**Comment by webard** [comment]
> It was not the package! It was my setup. I rolled my keys and also added my domain to webrtc (not sure if related), but in anycase, it works beautifully. Nice work, this is an incredible package!

Probably I missed one step in Zadarma configuration in README - adding domain in WebRTC tab.
